const normalComponents = {
  Box: `<Box></Box>`,
  Text: `<Text>Text value</Text>`,
  Button: `<Button>Button Text</Button>`,
  Heading: `<Heading>Heading Text</Heading>`,
  Badge: `<Badge>Badge</Badge>`,
  Avatar: `<Avatar />`,
  AvatarGroup: `<AvatarGroup spacing={-3} max={3} size="md"></AvatarGroup>`,
  Checkbox: `<Checkbox>Label checkbox</Checkbox>`,
  Flex: `<Flex></Flex>`,
  AspectRatio: `  <AspectRatio></AspectRatio>`,
  Grid: `<Grid templateColumns="repeat(5, 1fr)" gap={6} ></Grid>`,
  Icon: `<Icon as={CopyIcon} />`,
  IconButton: `<IconButton aria-label="icon" icon={<CopyIcon />}/>`,
  CircularProgress: `<CircularProgress value={50} size="48px" />`,
  CloseButton: `<CloseButton />`,
  Code: `<Code>Code value</Code>`,
  Divider: `<Divider borderColor="blackAlpha.500" />`,
  Link: `<Link>Link text</Link>`,
  Input: `<Input />`,
  Image: `<Image src='https://dummyimage.com/100x100' height="100px" width="100px" />`,
  Progress: `<Progress value={50} />`,
  Radio: `<Radio>Radio</Radio>`,
  RadioGroup: `<RadioGroup></RadioGroup>`,
  SimpleGrid: `<SimpleGrid columns={2} spacingX={1} spacingY={1}></SimpleGrid>`,
  Spinner: `<Spinner />`,
  Select: `<Select />`,
  Stack: `<Stack></Stack>`,
  Switch: `<Switch />`,
  Tag: `<Tag>Tag name</Tag>`,
  Textarea: `<Textarea />`,
}

export default normalComponents
