declare module 'css-to-object'
declare module '@babel/standalone'
declare module '@babel/plugin-syntax-jsx'
declare module '@babel/helper-plugin-utils'
declare module '@babel/template'
declare module 'prettier-standalone'
